/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Coordinador;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author REYCOG
 */
public class FrmEvaluacionInteligencia extends javax.swing.JFrame {
 Coordinador miCoordinador;

    public void setMiCoordinador(Coordinador miCoordinador) {
        this.miCoordinador = miCoordinador;
    }
    /**
     * Creates new form FrmInicioSesion
     */
    public FrmEvaluacionInteligencia() {
        initComponents();
    }
   public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Img/logo.png"));
        //Metodo para asignar el icono de pestaña y de la barra de tareas

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        txtNumeroPregunta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelInicioAdmi1 = new javax.swing.JLabel();
        btnIngresarAdmiLogin = new javax.swing.JButton();
        txtDominoArriba = new javax.swing.JComboBox<>();
        btnCancelarAdmiLogin = new javax.swing.JButton();
        labelpregunta = new javax.swing.JLabel();
        txtDominoAbajo = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        labelInicioAdmi = new javax.swing.JLabel();
        labelFondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEPENIPSMER - INICIO SESION");
        setIconImage(getIconImage());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeroPregunta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(txtNumeroPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 80, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Analice detenidamente la imagen de los dominós y selecciona la opción que le parezca \ncorrecta en cada pregunta, procure no dejar ninguna sin seleccionar. \n\nEn cada una de las 48 pruebas hay un grupo de fichas de dominó y un espacio en \nblanco, el objetivo en este caso será calcular según la lógica qué número le corresponde a la ficha");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 800, 220));

        labelInicioAdmi1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indicaciones ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel4.add(labelInicioAdmi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 310));

        btnIngresarAdmiLogin.setText("Siguiente");
        jPanel4.add(btnIngresarAdmiLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 750, 160, 40));

        txtDominoArriba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0", "1", "2", "3", "4", "5", "6" }));
        jPanel4.add(txtDominoArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));

        btnCancelarAdmiLogin.setText("Finalizar evaluación");
        jPanel4.add(btnCancelarAdmiLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 750, 160, 40));

        labelpregunta.setBackground(new java.awt.Color(0, 0, 0));
        labelpregunta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelpregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Inteligencia/1.PNG"))); // NOI18N
        jPanel4.add(labelpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        txtDominoAbajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0", "1", "2", "3", "4", "5", "6" }));
        jPanel4.add(txtDominoAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, -1, -1));

        jLabel43.setBackground(new java.awt.Color(0, 0, 0));
        jLabel43.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel43.setText("Seleccione el domino:");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        jLabel42.setBackground(new java.awt.Color(0, 0, 0));
        jLabel42.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel42.setText("Prueba:");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        labelInicioAdmi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluación de inteligencia ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel4.add(labelInicioAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1030, 470));

        labelFondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondoPantalla.png"))); // NOI18N
        labelFondoPantalla.setMaximumSize(new java.awt.Dimension(500, 500));
        labelFondoPantalla.setMinimumSize(new java.awt.Dimension(500, 500));
        labelFondoPantalla.setName(""); // NOI18N
        jPanel4.add(labelFondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -50, 1080, 940));

        jScrollPane2.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAdmiLogin;
    private javax.swing.JButton btnIngresarAdmiLogin;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelFondoPantalla;
    private javax.swing.JLabel labelInicioAdmi;
    private javax.swing.JLabel labelInicioAdmi1;
    private javax.swing.JLabel labelpregunta;
    private javax.swing.JComboBox<String> txtDominoAbajo;
    private javax.swing.JComboBox<String> txtDominoArriba;
    private javax.swing.JTextField txtNumeroPregunta;
    // End of variables declaration//GEN-END:variables
}
