/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Coordinador;
import java.awt.Image;
import java.awt.Toolkit;
import Vista.*;
import InterfacesEvaluacionEmocional.frmIndicacionesEvaluacionEmocional;

/**
 *
 * @author REYCOG
 */
public class FrmMenuEvaluacion extends javax.swing.JFrame {

    Coordinador miCoordinador;

    /**
     * Creates new form FrmInicioSesion
     */
    public FrmMenuEvaluacion() {
        initComponents();
        this.setResizable(false);
    }

    public void setMiCoordinador(Coordinador miCoordinador) {
        this.miCoordinador = miCoordinador;
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Img/logo.png"));
        //Metodo para asignar el icono de pestaña y de la barra de tareas

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnEnviarEvaluaci = new javax.swing.JButton();
        checkBoxInteligencia = new javax.swing.JCheckBox();
        btnCancelarEvalu = new javax.swing.JButton();
        btnRealizarInteligenciaEval = new javax.swing.JButton();
        btnRealizarProyectiEval = new javax.swing.JButton();
        checkBoxPersonalidad = new javax.swing.JCheckBox();
        checkBoxProyectiva = new javax.swing.JCheckBox();
        btnIngresarAdmiLogin2 = new javax.swing.JButton();
        checkBoxEmocional = new javax.swing.JCheckBox();
        btnSalir = new javax.swing.JButton();
        btnRealizarEmocionalEval = new javax.swing.JButton();
        labelInicioAdmi = new javax.swing.JLabel();
        labelFondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEPENIPSMER - INICIO SESION");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviarEvaluaci.setText("Ingresar a la evaluación");
        btnEnviarEvaluaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEvaluaciActionPerformed(evt);
            }
        });
        jPanel4.add(btnEnviarEvaluaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 190, 40));

        checkBoxInteligencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkBoxInteligencia.setText("Realizada");
        jPanel4.add(checkBoxInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        btnCancelarEvalu.setText("Cancelar");
        btnCancelarEvalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEvaluActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelarEvalu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 160, 40));

        btnRealizarInteligenciaEval.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRealizarInteligenciaEval.setText("Realizar evaluación de inteligencia");
        btnRealizarInteligenciaEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarInteligenciaEvalActionPerformed(evt);
            }
        });
        jPanel4.add(btnRealizarInteligenciaEval, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 460, 40));

        btnRealizarProyectiEval.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRealizarProyectiEval.setText("Realizar evaluación de proyectividad");
        btnRealizarProyectiEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarProyectiEvalActionPerformed(evt);
            }
        });
        jPanel4.add(btnRealizarProyectiEval, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 460, 40));

        checkBoxPersonalidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkBoxPersonalidad.setText("Realizada");
        jPanel4.add(checkBoxPersonalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        checkBoxProyectiva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkBoxProyectiva.setText("Realizada");
        jPanel4.add(checkBoxProyectiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        btnIngresarAdmiLogin2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIngresarAdmiLogin2.setText("Realizar evaluación de personalidad");
        btnIngresarAdmiLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAdmiLogin2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnIngresarAdmiLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 460, 40));

        checkBoxEmocional.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkBoxEmocional.setText("Realizada");
        jPanel4.add(checkBoxEmocional, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 160, 40));

        btnRealizarEmocionalEval.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRealizarEmocionalEval.setText("Realizar evaluación de inteligencia emocional");
        btnRealizarEmocionalEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarEmocionalEvalActionPerformed(evt);
            }
        });
        jPanel4.add(btnRealizarEmocionalEval, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 460, 40));

        labelInicioAdmi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menú de evaluaciones psicológicas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel4.add(labelInicioAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 660));

        labelFondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondoPantalla2.png"))); // NOI18N
        labelFondoPantalla.setMaximumSize(new java.awt.Dimension(500, 500));
        labelFondoPantalla.setMinimumSize(new java.awt.Dimension(500, 500));
        labelFondoPantalla.setName(""); // NOI18N
        jPanel4.add(labelFondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarEvaluaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEvaluaciActionPerformed

    }//GEN-LAST:event_btnEnviarEvaluaciActionPerformed

    private void btnCancelarEvaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEvaluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEvaluActionPerformed

    private void btnRealizarInteligenciaEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarInteligenciaEvalActionPerformed
    miCoordinador.mostrarFmrEvaluacionInt();
    miCoordinador.cerrarFmrMenuEvaluacion();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarInteligenciaEvalActionPerformed

    private void btnRealizarProyectiEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarProyectiEvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarProyectiEvalActionPerformed

    private void btnIngresarAdmiLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAdmiLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarAdmiLogin2ActionPerformed

    private void btnRealizarEmocionalEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarEmocionalEvalActionPerformed
        frmIndicacionesEvaluacionEmocional e = new frmIndicacionesEvaluacionEmocional();
        e.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarEmocionalEvalActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        miCoordinador.cerrarFmrMenuEvaluacion();
        miCoordinador.mostrarFmrInicioSesion();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEvalu;
    private javax.swing.JButton btnEnviarEvaluaci;
    private javax.swing.JButton btnIngresarAdmiLogin2;
    private javax.swing.JButton btnRealizarEmocionalEval;
    private javax.swing.JButton btnRealizarInteligenciaEval;
    private javax.swing.JButton btnRealizarProyectiEval;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox checkBoxEmocional;
    private javax.swing.JCheckBox checkBoxInteligencia;
    private javax.swing.JCheckBox checkBoxPersonalidad;
    private javax.swing.JCheckBox checkBoxProyectiva;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelFondoPantalla;
    private javax.swing.JLabel labelInicioAdmi;
    // End of variables declaration//GEN-END:variables
}
